<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: #077b19;
        }
        h2 {
            color: #b1c7ac;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://kpfu.ru/portal/docs/F_1777802040/logo.itis.jpg" alt="">
<h2><a href="${server_url}/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>
